# -*- coding: utf-8 -*-
"""SevastopolAI_v1_NoLLM"

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/104TbwrpX06Rsq8UfLFZ8osz5AcztmQji
"""

!pip install aiogram requests asyncio

import pandas as pd
import asyncio

# ID твоей таблицы
SPREADSHEET_ID = '1RaHoS_8Ov-kNKSZJK015ceC6H3fsWnW-D-8Yee4ckQI'

# Сюда бот загрузит всю таблицу один раз при старте и будет хранить в памяти для мгновенной выдачи
TABLE_CACHE = {
    "Где поесть": [],
    "Локации": [],
    "Маршруты": [],
    "События": []
}

async def update_sheets_cache():
    """
    Фоновая задача: скачивает таблицу и полностью обновляет кэш в памяти.
    Работает асинхронно, карусели при этом не зависают.
    """
    url = f"https://docs.google.com/spreadsheets/d/{SPREADSHEET_ID}/export?format=xlsx"

    while True:
        try:
            print("🔄 [КЭШ] Начинаю фоновое обновление данных из Google Sheets...")

            # Читаем Excel асинхронно, чтобы чтение тяжелого файла не вешало бота
            loop = asyncio.get_event_loop()
            excel_file = await loop.run_in_executor(None, pd.ExcelFile, url)
            sheet_names = excel_file.sheet_names
            cleaned_sheets = {name.strip(): name for name in sheet_names}

            # 1. Кэшируем вкладку "Где поесть?"
            target_food = "Где поесть?" if "Где поесть?" in cleaned_sheets else sheet_names[0]
            df_food = await loop.run_in_executor(None, lambda: pd.read_excel(url, sheet_name=target_food).fillna(''))
            TABLE_CACHE["Где поесть"] = df_food.to_dict(orient='records')
            print(f"👍 [КЭШ] Вкладка 'Где поесть' успешно загружена. Строк: {len(TABLE_CACHE['Где поесть'])}")

            # 2. Кэшируем остальные важные вкладки
            for sheet_key in ["Локации", "Маршруты", "События"]:
                if sheet_key in cleaned_sheets:
                    real_name = cleaned_sheets[sheet_key]
                    df_other = await loop.run_in_executor(None, lambda: pd.read_excel(url, sheet_name=real_name).fillna(''))
                    TABLE_CACHE[sheet_key] = df_other.to_dict(orient='records')
                    print(f"👍 [КЭШ] Вкладка '{sheet_key}' успешно загружена. Строк: {len(TABLE_CACHE[sheet_key])}")
                else:
                    print(f"⚠️ [КЭШ] Вкладка '{sheet_key}' не найдена в Google-таблице.")

            print("✅ [КЭШ] Все данные успешно обновлены в памяти и готовы к моментальной выдаче!")

        except Exception as e:
            print(f"❌ [КЭШ] Ошибка при фоновом обновлении таблицы: {e}")

        # Повторяем процедуру каждые 10 минут (600 секунд)
        await asyncio.sleep(600)


def get_places_from_sheet(target_name: str):
    """
    Молниеносная функция: мгновенно берет данные из базы в оперативной памяти (TABLE_CACHE)
    """
    # ТВОИ НОВЫЕ СТРОГИЕ КАТЕГОРИИ ИЗ ТАБЛИЦЫ
    food_categories = ["Кофе", "Рестораны", "Кафе", "Пекарни", "Кондитерские", "Доставки"]

    if target_name in food_categories:
        all_rows = TABLE_CACHE.get("Где поесть", [])
        # Фильтруем строки по категории прямо в оперативной памяти
        filtered_data = [
            row for row in all_rows
            if str(row.get('Категория', '')).strip() == target_name
        ]
        print(f"⚡ [ПАМЯТЬ] Найдено мест в кэше для категории '{target_name}': {len(filtered_data)}")
        return filtered_data
    else:
        # Для Локаций, Маршрутов и Событий возвращаем сохраненный лист целиком
        data = TABLE_CACHE.get(target_name, [])
        print(f"⚡ [ПАМЯТЬ] Возвращаю лист '{target_name}' из кэше. Строк: {data}")
        return data

import logging
import asyncio
from aiogram import Bot, Dispatcher, types
from aiogram.filters import CommandStart

TG_TOKEN = "8927839211:AAHNfq5D1uOciVc3lEYyu3oNQGZTLLLqScw"

logging.basicConfig(level=logging.INFO)
bot = Bot(token=TG_TOKEN)
dp = Dispatcher()

print("Настройки есть !")

import urllib.parse  # Добавили для кодирования текста в шеринг-ссылки
from aiogram.types import InlineKeyboardMarkup, InlineKeyboardButton, ReplyKeyboardRemove, InputMediaPhoto, ReplyKeyboardMarkup, KeyboardButton
from aiogram.filters import CommandStart
from aiogram.fsm.context import FSMContext
from aiogram import F, types
import math
from datetime import datetime
import pandas as pd # Добавлено, так как pd.isna используется ниже

# Наш обновленный глобальный словарь категорий
cat_map = {
    "coffee": "Кофе",
    "rest": "Рестораны",
    "cafe": "Кафе",
    "bakery": "Пекарни",
    "sweets": "Кондитерские",
    "delivery": "Доставки"
}

# Реплай-клавиатура управления
main_reply_keyboard = ReplyKeyboardMarkup(
    keyboard=[
        [
            KeyboardButton(text="🏠 Главное меню"),
            KeyboardButton(text="💬 Связь")
        ]
    ],
    resize_keyboard=True,
    is_persistent=True
)

def calculate_distance(lat1, lon1, lat2, lon2):
    R = 6371000
    phi1 = math.radians(lat1)
    phi2 = math.radians(lat2)
    delta_phi = math.radians(lat2 - lat1)
    delta_lambda = math.radians(lon2 - lon1)

    a = math.sin(delta_phi / 2)**2 + math.cos(phi1) * math.cos(phi2) * math.sin(delta_lambda / 2)**2
    c = 2 * math.atan2(math.sqrt(a), math.sqrt(1 - a))
    return R * c

async def edit_or_reply_text(call: types.CallbackQuery, text: str, reply_markup):
    if call.message.photo:
        await call.message.delete()
        await call.message.answer(text=text, reply_markup=reply_markup)
    else:
        await call.message.edit_text(text=text, reply_markup=reply_markup)

# 1. Карусель для ЕДЫ
def create_carousel_card(places, index: int, category_key: str):

    if not places or index < 0 or index >= len(places):
        return "Заведение не найдено", None, None

    item = places[index]
    total = len(places)

    name = item.get('Название', 'Без названия')
    photo_url = str(item.get('Ссылка на фото', '')).strip()
    description = item.get('Описание', '')
    address = item.get('Адрес', 'Адрес не указан')
    district = item.get('Район', '')
    coords = str(item.get('Координаты', '')).strip()
    phone = item.get('Телефон', '')
    work_time = item.get('Bремя работы', item.get('Время работы', ''))

    distance_block = ""
    if "distance" in item:
        dist = item["distance"]
        if dist < 1000:
            distance_block = f"\n📍 <b>Расстояние до вас:</b> ~{int(dist)} м"
        else:
            distance_block = f"\n📍 <b>Расстояние до вас:</b> ~{dist/1000:.1f} км"

    if coords:
        clean_coords = coords.replace(' ', '')
        maps_url = f"https://yandex.ru/maps/?text={clean_coords}"
        address_text = f"{address} ({district})" if district else address
        address_block = f"📍 <b>Адрес:</b> {address_text} — <a href='{maps_url}'>🗺 Показать на карте</a>{distance_block}"
    else:
        address_text = f"{address} ({district})" if district else address
        address_block = f"📍 <b>Адрес:</b> {address_text}{distance_block}"

    text = f"<b>{name}</b>\n\n"
    text += f"{address_block}\n\n"
    if work_time:
        text += f"🕒 <b>Время работы:</b> {work_time}\n\n"
    if phone:
        text += f"📞 <b>Телефон:</b> {phone}\n\n"
    if description:
        text += f"💬 <b>О заведении:</b>\n{description}"

    inline_keyboard = []
    site_url = str(item.get('Сайт', '')).strip()
    if site_url and site_url.lower() != 'nan' and site_url != '':
        if not site_url.startswith('http://') and not site_url.startswith('https://'):
            site_url = 'https://' + site_url
        inline_keyboard.append([InlineKeyboardButton(text="🌐 Еще и сайт есть", url=site_url)])
    vk_url = str(item.get('Bконтакте', item.get('Вконтакте', ''))).strip()
    tg_url = str(item.get('Telegram', '')).strip()
    insta_url = str(item.get('Instagram', '')).strip()

    social_row = []
    if vk_url: social_row.append(InlineKeyboardButton(text="👥 ВКонтакте", url=vk_url))
    if tg_url: social_row.append(InlineKeyboardButton(text="📱 Telegram", url=tg_url))
    if insta_url: social_row.append(InlineKeyboardButton(text="📸 Instagram", url=insta_url))
    if social_row: inline_keyboard.append(social_row)

    # --- ИСПРАВЛЕННЫЙ БЛОК ДЛЯ КНОПКИ ШЕРИНГА (ЕДА) ---
    share_text = f"🔥 Нашёл классное место в Севастополе: «{name}»\n\n📍 Адрес: {address_text}"
    if work_time: share_text += f"\n🕒 Время работы: {work_time}"
    if phone: share_text += f"\n📞 Телефон: {phone}"
    share_text += "\n\nСкинула Кира из Sevastopol AI: https://t.me/SevastopolAiBot"

    share_link = f"https://yandex.ru/maps/?text={coords.replace(' ', '')}" if coords else "https://t.me"

    encoded_share_text = urllib.parse.quote(share_text)
    encoded_share_link = urllib.parse.quote(share_link)
    share_url = f"https://t.me/share/url?url={encoded_share_link}&text={encoded_share_text}"

    inline_keyboard.append([InlineKeyboardButton(text="⭐ Сохранить / Скинуть другу", url=share_url)])
    # --------------------------------------------------

    prev_index = (index - 1) % total
    next_index = (index + 1) % total

    inline_keyboard.append([
        InlineKeyboardButton(text="⬅️ Назад", callback_data=f"page_{category_key}_{prev_index}"),
        InlineKeyboardButton(text=f"🔹 {index + 1} / {total} 🔹", callback_data="keep_calm"),
        InlineKeyboardButton(text="Вперед ➡️", callback_data=f"page_{category_key}_{next_index}")
    ])

    if category_key == "nearfood":
        inline_keyboard.append([InlineKeyboardButton(text="🔙 К списку локаций", callback_data="loc_menu")])
    else:
        inline_keyboard.append([InlineKeyboardButton(text="🔙 Вернуться к фильтрам", callback_data=f"back_to_cat_{category_key}")])

    markup = InlineKeyboardMarkup(inline_keyboard=inline_keyboard)
    photo_url = str(item.get('Ссылка на фото', '')).strip()
    return text, markup, photo_url

# 2. Карусель для ЛОКАЦИЙ
def create_location_carousel(places, index: int, category_key: str):
    if not places or index < 0 or index >= len(places):
        return "Локация не найдена", None, None

    item = places[index]
    total = len(places)

    name = item.get('Название', 'Без названия')
    description = item.get('Описание', '')
    orientir = item.get('Ориентир', 'Не указан')
    coords = str(item.get('Координаты', '')).strip()

    text = f"📍 <b>{name}</b>\n\n"
    text += f"🗺 <b>Ориентир:</b> {orientir}\n\n"
    if description:
        text += f"💬 <b>Описание:</b>\n{description}"

    inline_keyboard = []
    if coords and coords not in ["", "None", "nan"]:
        clean_coords = coords.replace(' ', '')
        inline_keyboard.append([InlineKeyboardButton(text="🗺 Открыть карту", url=f"https://yandex.ru/maps/?text={clean_coords}")])
        inline_keyboard.append([InlineKeyboardButton(text="🍔 Съестное рядом", callback_data=f"foodnear_loc_{category_key}_{index}")])

    # --- ИСПРАВЛЕННЫЙ БЛОК ДЛЯ КНОПКИ ШЕРИНГА (ЛОКАЦИИ) ---
    share_text = f"📍 Крутая локация в Севастополе: {name}\n\n🗺 Ориентир: {orientir}"
    share_text += "\n\nСкинула Кира из Sevastopol AI: https://t.me/SevastopolAiBot"
    share_link = f"https://yandex.ru/maps/?text={coords.replace(' ', '')}" if (coords and coords not in ["", "None", "nan"]) else "https://t.me"

    encoded_share_text = urllib.parse.quote(share_text)
    encoded_share_link = urllib.parse.quote(share_link)
    share_url = f"https://t.me/share/url?url={encoded_share_link}&text={encoded_share_text}"

    inline_keyboard.append([InlineKeyboardButton(text="⭐ Сохранить / Скинуть другу", url=share_url)])
    # ------------------------------------------------------

    prev_index = (index - 1) % total
    next_index = (index + 1) % total

    inline_keyboard.append([
        InlineKeyboardButton(text="⬅️ Назад", callback_data=f"loc_page_{category_key}_{prev_index}"),
        InlineKeyboardButton(text=f"🔹 {index + 1} / {total} 🔹", callback_data="keep_calm"),
        InlineKeyboardButton(text="Вперед ➡️", callback_data=f"loc_page_{category_key}_{next_index}")
    ])
    inline_keyboard.append([InlineKeyboardButton(text="🔙 К категориям локаций", callback_data="loc_menu")])

    markup = InlineKeyboardMarkup(inline_keyboard=inline_keyboard)
    photo_url = str(item.get('Ссылка на фото', '')).strip()
    return text, markup, photo_url

# 3. Карусель для МАРШРУТОВ
def create_route_carousel(places, index: int, category_key: str):
    if not places or index < 0 or index >= len(places):
        return "Маршрут не найден", None, None

    item = places[index]
    total = len(places)

    name = item.get('Название', 'Без названия')
    description = item.get('Описание', '')
    duration = item.get('Длина/Время', 'Не указано')
    difficulty = item.get('Сложность', 'Не указана')
    map_url = str(item.get('Ссылка на карту', '')).strip()
    coords = str(item.get('Координаты', '')).strip()

    text = f"🗺 <b>{name}</b>\n\n"
    text += f"⏱ <b>Длина/Время:</b> {duration}\n"
    text += f"📊 <b>Сложность:</b> {difficulty}\n\n"
    if description:
        text += f"📝 <b>Маршрут:</b>\n{description}"

    inline_keyboard = []
    if map_url and map_url.startswith("http"):
        inline_keyboard.append([InlineKeyboardButton(text="🗺 Открыть карту маршрута", url=map_url)])

    if coords and coords not in ["", "None", "nan"]:
        inline_keyboard.append([InlineKeyboardButton(text="🍔 Съестное рядом", callback_data=f"foodnear_rt_{category_key}_{index}")])

    # --- ИСПРАВЛЕННЫЙ БЛОК ДЛЯ КНОПКИ ШЕРИНГА (МАРШРУТЫ) ---
    share_text = f"🗺 Интересный маршрут в Севастополе: {name}\n\n⏱ Длина/Время: {duration}\n📊 Сложность: {difficulty}"
    share_text += "\n\nСкинула Кира из Sevastopol AI: https://t.me/SevastopolAiBot"
    share_link = map_url if (map_url and map_url.startswith("http")) else "https://t.me"

    encoded_share_text = urllib.parse.quote(share_text)
    encoded_share_link = urllib.parse.quote(share_link)
    share_url = f"https://t.me/share/url?url={encoded_share_link}&text={encoded_share_text}"

    inline_keyboard.append([InlineKeyboardButton(text="⭐ Сохранить / Скинуть другу", url=share_url)])
    # ------------------------------------------------------

    prev_index = (index - 1) % total
    next_index = (index + 1) % total

    inline_keyboard.append([
        InlineKeyboardButton(text="⬅️ Назад", callback_data=f"route_page_{category_key}_{prev_index}"),
        InlineKeyboardButton(text=f"🔹 {index + 1} / {total} 🔹", callback_data="keep_calm"),
        InlineKeyboardButton(text="Вперед ➡️", callback_data=f"route_page_{category_key}_{next_index}")
    ])
    inline_keyboard.append([InlineKeyboardButton(text="🔙 К категориям маршрутов", callback_data="routes_menu")])

    markup = InlineKeyboardMarkup(inline_keyboard=inline_keyboard)
    photo_url = str(item.get('Ссылка на фото', '')).strip()
    return text, markup, photo_url

def get_main_inline_kb():
    kb = InlineKeyboardMarkup(inline_keyboard=[
        [InlineKeyboardButton(text="🍽 Где поесть", callback_data="food_menu"),
         InlineKeyboardButton(text="📍 Локации", callback_data="loc_menu")],
        [InlineKeyboardButton(text="📅 События", callback_data="events_menu"),
         InlineKeyboardButton(text="🗺 Маршруты", callback_data="routes_menu")]
    ])
    return kb

@dp.callback_query()
async def callback_handler(call: types.CallbackQuery, state: FSMContext):
    data = call.data

    if data == "main_menu":
        await state.clear()
        await edit_or_reply_text(call, "Выбирай категорию:", get_main_inline_kb())

    elif data == "food_menu":
        await state.clear()
        kb = InlineKeyboardMarkup(inline_keyboard=[
            [InlineKeyboardButton(text="☕ Кофе", callback_data="cat_coffee"),
             InlineKeyboardButton(text="🍽 Рестораны", callback_data="cat_rest")],
            [InlineKeyboardButton(text="🍕 Кафе", callback_data="cat_cafe"),
             InlineKeyboardButton(text="🥐 Пекарни", callback_data="cat_bakery")],
            [InlineKeyboardButton(text="🍰 Кондитерские", callback_data="cat_sweets"),
             InlineKeyboardButton(text="📦 Доставки", callback_data="cat_delivery")],
            [InlineKeyboardButton(text="⬅️ Назад", callback_data="main_menu")]
        ])
        await edit_or_reply_text(call, "Шо именно мы ищем? Выбирай категорию: 👇", kb)

    elif data.startswith("cat_") or data.startswith("back_to_cat_"):
        category = data.split("_")[-1]

        messages_map = {
            "coffee": "Отлично, ищем лучший кофе в городе! ☕ Как тебе удобнее выбрать?",
            "rest": "Хочется изысканной кухни и классной атмосферы? 🍽 Выбирай вариант:",
            "cafe": "Ищешь уютное место посидеть и перекусить? 🍕 Как смотрим?",
            "bakery": "За свежей выпечкой и хрустящими круассанами сюда! 🥐 С чего начнем поиски?",
            "sweets": "Время побаловать себя сладеньким! 🍰 Где ищем кондитерскую?",
            "delivery": "Чилл дома, а еда сама едет к тебе? 📦 Выбирай формат:"
        }
        custom_text = messages_map.get(category, "Выбирай вариант поиска: 👇")
        back_target = "food_menu"

        kb = InlineKeyboardMarkup(inline_keyboard=[
            [InlineKeyboardButton(text="📍 Рядом со мной", callback_data=f"filter_near_{category}")],
            [InlineKeyboardButton(text="🗺 НА РАЙОНЕ", callback_data=f"filter_dist_{category}")],
            [InlineKeyboardButton(text="📋 Все списком", callback_data=f"filter_all_{category}")],
            [InlineKeyboardButton(text="⬅️ Назад", callback_data=back_target)]
        ])
        await edit_or_reply_text(call, custom_text, kb)

    elif data.startswith("filter_dist_"):
        category = data.split("_")[2]
        sheet_cat = cat_map.get(category, "Кофе")
        places = get_places_from_sheet(sheet_cat)
        if not places:
            await call.answer("Ничего не найдено 😔", show_alert=True)
            return
        districts = set([p.get("Район", "") for p in places if p.get("Район", "")])
        if not districts:
            await call.answer("В таблице не заполнены районы!", show_alert=True)
            return
        from aiogram.utils.keyboard import InlineKeyboardBuilder
        builder = InlineKeyboardBuilder()
        for district in sorted(districts):
            builder.button(text=district, callback_data=f"subdist_{category}_{district}")
        builder.adjust(2)
        builder.button(text="⬅️ Назад", callback_data=f"cat_{category}")
        builder.adjust(2, 1)
        await edit_or_reply_text(call, "Выбери интересующий район города: 👇", builder.as_markup())
        await call.answer()

    elif data.startswith("subdist_"):
        parts = data.split("_")
        category = parts[1]
        district_name = parts[2]
        sheet_cat = cat_map.get(category, "Кофе")
        places = get_places_from_sheet(sheet_cat)
        filtered_places = [p for p in places if str(p.get("Район", "")).strip() == district_name]
        if not filtered_places:
            await call.answer("В этом районе нет заведений!", show_alert=True)
            return
        await state.update_data(filtered_places=filtered_places, current_category=category)
        text, markup, photo_url = create_carousel_card(filtered_places, 0, category)
        await call.message.delete()
        if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
        else: await call.message.answer(text=text, reply_markup=markup, parse_mode="HTML")
        await call.answer()

    elif data.startswith("filter_near_"):
        category = data.split("_")[2]
        await state.update_data(location_target_category=category, menu_source="food")
        location_keyboard = ReplyKeyboardMarkup(keyboard=[[KeyboardButton(text="📍 Отправить геопозицию", request_location=True)]], resize_keyboard=True, one_time_keyboard=True)
        disclaimer_text = (
            "Чтобы я нашёл заведения в шаговой доступности, нажми кнопку «📍 Отправить геопозицию» в самом низу экрана 👇\n\n"
            "⚠️ <b>Внимание:</b> если у тебя включен VPN или шалят глушилки, координаты могут знатно заглючить, "
            "а расстояния — стать космическими. Если цифры покажутся странными, не паникуй "
            "и просто используй кнопку «🗺 НА РАЙОНЕ»!"
        )
        await call.message.answer(text=disclaimer_text, reply_markup=location_keyboard, parse_mode="HTML")
        await call.answer()

    elif data.startswith("filter_all_"):
        category = data.split("_")[2]
        sheet_cat = cat_map.get(category, "Кофе")
        places = get_places_from_sheet(sheet_cat)
        if not places:
            await call.answer("Ничего не найдено 😔", show_alert=True)
            return
        text, markup, photo_url = create_carousel_card(places, 0, category)
        await call.message.delete()
        if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
        else: await call.message.answer(text=text, reply_markup=markup, parse_mode="HTML")

    elif data.startswith("foodnear_"):
        parts = data.split("_")
        place_type = parts[1] # "loc" или "rt"
        category = parts[2]
        index = int(parts[3])

        state_data = await state.get_data()
        if place_type == "loc":
            places = state_data.get("loc_places") or [r for r in get_places_from_sheet("Локации") if category.lower() in str(r.get('Категория', '')).lower()]
        else:
            places = state_data.get("rt_places") or [r for r in get_places_from_sheet("Маршруты") if category.lower() in str(r.get('Категория', '')).lower()]

        if not places or index >= len(places):
            await call.answer("Место не найдено 😔", show_alert=True)
            return

        target_place = places[index]
        coords_str = str(target_place.get('Координаты', '')).strip()

        if not coords_str or ',' not in coords_str:
            await call.answer("У этого места нет координат для поиска еды 😔", show_alert=True)
            return

        try:
            lat_str, lon_str = coords_str.split(",")
            target_lat = float(lat_str.strip())
            target_lon = float(lon_str.strip())
        except:
            await call.answer("Ошибка в координатах локации.", show_alert=True)
            return

        all_food_places = []
        for sheet_cat in cat_map.values():
            food_items = get_places_from_sheet(sheet_cat)
            if food_items:
                all_food_places.extend(food_items)

        places_with_distance = []
        for p in all_food_places:
            p_copy = p.copy()
            f_coords = str(p_copy.get("Координаты", "")).strip()
            if f_coords and "," in f_coords:
                try:
                    f_lat, f_lon = f_coords.split(",")
                    dist = calculate_distance(target_lat, target_lon, float(f_lat.strip()), float(f_lon.strip()))
                    p_copy["distance"] = dist
                    places_with_distance.append(p_copy)
                except: continue

        if not places_with_distance:
            await call.answer("Рядом ничего вкусного не найдено 😔", show_alert=True)
            return

        places_with_distance.sort(key=lambda x: x.get("distance", 999999))
        nearest_food = places_with_distance[:10]

        await state.update_data(filtered_places=nearest_food, current_category="nearfood")

        text, markup, photo_url = create_carousel_card(nearest_food, 0, "nearfood")
        await call.message.delete()
        if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
        else: await call.message.answer(text=text, reply_markup=markup, parse_mode="HTML")
        await call.answer()

    elif data.startswith("page_"):
        parts = data.split("_")
        category = parts[1]
        index = int(parts[2])
        state_data = await state.get_data()

        if category == "nearfood":
            places = state_data.get("filtered_places")
        else:
            places = state_data.get("filtered_places") if state_data.get("current_category") == category else get_places_from_sheet(cat_map.get(category, "Кофе"))
        if not places: return
        text, markup, photo_url = create_carousel_card(places, index, category)
        try:
            if photo_url and call.message.photo:
                await call.message.edit_media(media=InputMediaPhoto(media=photo_url, caption=text, parse_mode="HTML"), reply_markup=markup)
            else:
                await call.message.delete()
                if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
                else: await call.message.edit_text(text=text, reply_markup=markup, parse_mode="HTML")
        except Exception: pass
        await call.answer()

    # ЛОКАЦИИ 📍
    elif data == "loc_menu":
        kb = InlineKeyboardMarkup(inline_keyboard=[
            [InlineKeyboardButton(text="🏖 Пляжи", callback_data="locselect_Пляжи"),
             InlineKeyboardButton(text="🔭 Смотровые", callback_data="locselect_Смотровые")],
            [InlineKeyboardButton(text="🌅 Закаты", callback_data="locselect_Закаты"),
             InlineKeyboardButton(text="💎 Hidden Gems", callback_data="locselect_Hidden Gems")],
            [InlineKeyboardButton(text="🚶 Прогулки", callback_data="locselect_Прогулки")],
            [InlineKeyboardButton(text="⬅️ В главное меню", callback_data="main_menu")]
        ])
        await edit_or_reply_text(call, "Выбери интересующую категорию локаций: 👇", kb)
        await call.answer()

    elif data.startswith("locselect_"):
        category = data.split("_")[1]
        all_locations = get_places_from_sheet("Локации")
        found = [r for r in all_locations if category.lower() in str(r.get('Категория', '')).lower()]

        if not found:
            await call.answer(f"Локации из категории «{category}» пока наполняются! 🌀", show_alert=True)
            return

        await state.update_data(loc_places=found)
        text, markup, photo_url = create_location_carousel(found, 0, category)
        await call.message.delete()
        if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
        else: await call.message.answer(text=text, reply_markup=markup, parse_mode="HTML")
        await call.answer()

    elif data.startswith("loc_page_"):
        parts = data.split("_")
        category = parts[2]
        index = int(parts[3])
        state_data = await state.get_data()
        places = state_data.get("loc_places")
        if not places:
            all_locations = get_places_from_sheet("Локации")
            places = [r for r in all_locations if category.lower() in str(r.get('Категория', '')).lower()]

        text, markup, photo_url = create_location_carousel(places, index, category)
        try:
            if photo_url and call.message.photo:
                await call.message.edit_media(media=InputMediaPhoto(media=photo_url, caption=text, parse_mode="HTML"), reply_markup=markup)
            else:
                await call.message.delete()
                if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
                else: await call.message.edit_text(text=text, reply_markup=markup, parse_mode="HTML")
        except Exception: pass
        await call.answer()

    # МАРШРУТЫ 🗺
    elif data == "routes_menu":
        kb = InlineKeyboardMarkup(inline_keyboard=[
            [InlineKeyboardButton(text="🥾 Пешие", callback_data="rtselect_Пешие"),
             InlineKeyboardButton(text="🚲 Вело", callback_data="rtselect_Велосипед")],
            [InlineKeyboardButton(text="🚗 Авто", callback_data="rtselect_Авто"),
             InlineKeyboardButton(text="🌊 Вода", callback_data="rtselect_Вода")],
            [InlineKeyboardButton(text="⬅️ В главное меню", callback_data="main_menu")]
        ])
        await edit_or_reply_text(call, "Выбери формат твоего трипа: 👇", kb)
        await call.answer()

    elif data.startswith("rtselect_"):
        category = data.split("_")[1]
        all_routes = get_places_from_sheet("Маршруты")
        found = [r for r in all_routes if category.lower() in str(r.get('Категория', '')).lower()]

        if not found:
            await call.answer(f"Маршруты типа «{category}» сейчас прокладываются! 🧭", show_alert=True)
            return

        await state.update_data(rt_places=found)
        text, markup, photo_url = create_route_carousel(found, 0, category)
        await call.message.delete()
        if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
        else: await call.message.answer(text=text, reply_markup=markup, parse_mode="HTML")
        await call.answer()

    elif data.startswith("route_page_"):
        parts = data.split("_")
        category = parts[2]
        index = int(parts[3])
        state_data = await state.get_data()
        places = state_data.get("rt_places")
        if not places:
            all_routes = get_places_from_sheet("Маршруты")
            places = [r for r in all_routes if category.lower() in str(r.get('Категория', '')).lower()]

        text, markup, photo_url = create_route_carousel(places, index, category)
        try:
            if photo_url and call.message.photo:
                await call.message.edit_media(media=InputMediaPhoto(media=photo_url, caption=text, parse_mode="HTML"), reply_markup=markup)
            else:
                await call.message.delete()
                if photo_url: await call.message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
                else: await call.message.edit_text(text=text, reply_markup=markup, parse_mode="HTML")
        except Exception: pass
        await call.answer()

    # СОБЫТИЯ 📅
    elif data == "events_menu":
        events_list = get_places_from_sheet("События")
        current_date = datetime.now().date()
        upcoming_events = []

        for r in events_list:
            raw_date = r.get('Дата')

            if raw_date is None or (isinstance(raw_date, float) and pd.isna(raw_date)):
                continue

            if isinstance(raw_date, datetime):
                event_date = raw_date.date()
            else:
                date_str = str(raw_date).strip()
                if date_str in ["None", "nan", "NaT", ""]:
                    continue

                event_date = None
                for fmt in ("%d.%m.%Y", "%Y-%m-%d", "%d/%m/%Y"):
                    try:
                        event_date = datetime.strptime(date_str, fmt).date()
                        break
                    except ValueError:
                        continue

            if event_date and not pd.isna(event_date) and event_date >= current_date:
                upcoming_events.append((event_date, r))

        upcoming_events.sort(key=lambda x: x[0])

        if not upcoming_events:
            back_kb = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="⬅️ В главное меню", callback_data="main_menu")]])
            await call.message.edit_text("На ближайшие дни событий не найдено. Самое время устроить чилл! 🌅", reply_markup=back_kb)
        else:
            await call.message.delete()
            await call.message.answer("📅 <b>Ближайшие актуальные события Севастополя:</b>", parse_mode="HTML")

            for event_date, event in upcoming_events:
                formatted_date = event_date.strftime("%d.%m.%Y")
                text = (
                    f"📅 <b>{formatted_date}</b> | 📍 <b>{event.get('Место', 'Локация не указана')}</b>\n"
                    f"🎭 <b>{event.get('Название', 'Без названия')}</b>\n\n"
                    f"{event.get('Описание', '')}"
                )
                markup = None
                buy_url = str(event.get('Купить', '')).strip()
                if buy_url and buy_url.startswith("http"):
                    markup = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="🎟 Билеты / Подробнее", url=buy_url)]])

                photo = event.get('Ссылка на афишу', '')
                if photo and str(photo).startswith("http"):
                    try:
                        await call.message.answer_photo(photo=photo, caption=text, reply_markup=markup, parse_mode="HTML")
                    except:
                        await call.message.answer(text=text, reply_markup=markup, parse_mode="HTML")
                else:
                    await call.message.answer(text=text, reply_markup=markup, parse_mode="HTML")

            back_kb = InlineKeyboardMarkup(inline_keyboard=[[InlineKeyboardButton(text="⬅️ В главное меню", callback_data="main_menu")]])
            await call.message.answer("--- \n<i>Больше событий пока нет.</i>", reply_markup=back_kb, parse_mode="HTML")

        await call.answer()


@dp.message(F.text == "🏠 Главное меню")
async def process_main_menu_btn(message: types.Message, state: FSMContext):
    await state.clear()
    await message.answer("Вы вернулись в главное меню:", reply_markup=get_main_inline_kb())

@dp.message(F.text == "💬 Связь")
async def process_contact_btn(message: types.Message, state: FSMContext):
    await message.answer(
        "Есть вопросы, предложения или нашли ошибку?\n"
        "Напишите нам напрямую: @PavelYuRichRWA",
        parse_mode="HTML"
    )


@dp.message(CommandStart())
async def cmd_start(message: types.Message):
    welcome_text = (
        "Привет! Я — твой гид по Севастополю. \n"
        "Помогу найти лучшее место для еды, покажу интересные локации "
        "и расскажу, что происходит в городе. \n\n"
        "Выбирай, что тебя интересует:"
    )
    await message.answer("Панель управления загружена 👇", reply_markup=main_reply_keyboard)
    await message.answer(welcome_text, reply_markup=get_main_inline_kb())

# --- ПОЛНОСТЬЮ ВОССТАНОВЛЕННЫЙ И ДОПИСАННЫЙ ОБРАБОТЧИК ГЕОПОЗИЦИИ ---
@dp.message(F.location)
async def handle_user_location(message: types.Message, state: FSMContext):
    user_lat = message.location.latitude
    user_lon = message.location.longitude

    state_data = await state.get_data()
    category = state_data.get("location_target_category", "coffee")

    sheet_cat = cat_map.get(category, "Кофе")
    places = get_places_from_sheet(sheet_cat)

    if not places:
        await message.answer("Ошибка получения данных 😔", reply_markup=ReplyKeyboardRemove())
        return

    places_with_distance = []
    for place in places:
        p_copy = place.copy()
        coords_str = str(p_copy.get("Координаты", "")).strip()
        if coords_str and "," in coords_str:
            try:
                lat_str, lon_str = coords_str.split(",")
                place_lat = float(lat_str.strip())
                place_lon = float(lon_str.strip())

                distance = calculate_distance(user_lat, user_lon, place_lat, place_lon)
                p_copy["distance"] = distance
                places_with_distance.append(p_copy)
            except Exception: continue

    if not places_with_distance:
        await message.answer("Увы, не удалось рассчитать расстояние.", reply_markup=ReplyKeyboardRemove())
        return

    places_with_distance.sort(key=lambda x: x.get("distance", 999999))

    await message.answer("Секунду, ищу ближайшие...", reply_markup=ReplyKeyboardRemove())
    await state.update_data(filtered_places=places_with_distance, current_category=category)

    # Финальная склейка карусели и вывод пользователю первого (ближайшего) места
    text, markup, photo_url = create_carousel_card(places_with_distance, 0, category)

    if photo_url:
        await message.answer_photo(photo=photo_url, caption=text, reply_markup=markup, parse_mode="HTML")
    else:
        await message.answer(text=text, reply_markup=markup, parse_mode="HTML")

async def main():
    print("Вызываю первое обновление кэша таблиц...")
    # Запускаем фоновую задачу, которая будет обновлять кэш каждые 10 минут
    asyncio.create_task(update_sheets_cache())

    # Даем боту 3 секунды при старте, чтобы он успел скачать базу первый раз,
    # тогда кэш не будет пустым для первых запросов
    await asyncio.sleep(3)

    print("Удаляю старые вебхуки и запускаю бота...")
    await bot.delete_webhook(drop_pending_updates=True)

    print("🚀 Бот успешно запущен, кэширование активно и готов к моментальной работе!")
    try:
        await dp.start_polling(bot)
    finally:
        await bot.session.close()

# Запуск в среде Jupyter Notebook
await main()